export const initialState={
    MfacultyAt9:[],
    MfacultyAt10:[],
    MfacultyAt11:[],
    MfacultyAt12:[],
    MfacultyAt03:[],
    MfacultyAt04:[],

    TfacultyAt9:[],
    TfacultyAt10:[],
    TfacultyAt11:[],
    TfacultyAt12:[],
    TfacultyAt03:[],
    TfacultyAt04:[],

    WfacultyAt9:[],
    WfacultyAt10:[],
    WfacultyAt11:[],
    WfacultyAt12:[],
    WfacultyAt03:[],
    WfacultyAt04:[],

    THfacultyAt9:[],
    THfacultyAt10:[],
    THfacultyAt11:[],
    THfacultyAt12:[],
    THfacultyAt03:[],
    THfacultyAt04:[],

    FfacultyAt9:[],
    FfacultyAt10:[],
    FfacultyAt11:[],
    FfacultyAt12:[],
    FfacultyAt03:[],
    FfacultyAt04:[],

    CMfacultyAt9:[],
    CMfacultyAt10:[],
    CMfacultyAt11:[],
    CMfacultyAt12:[],
    CMfacultyAt03:[],
    CMfacultyAt04:[],

    CTfacultyAt9:[],
    CTfacultyAt10:[],
    CTfacultyAt11:[],
    CTfacultyAt12:[],
    CTfacultyAt03:[],
    CTfacultyAt04:[],

    CWfacultyAt9:[],
    CWfacultyAt10:[],
    CWfacultyAt11:[],
    CWfacultyAt12:[],
    CWfacultyAt03:[],
    CWfacultyAt04:[],

    CTHfacultyAt9:[],
    CTHfacultyAt10:[],
    CTHfacultyAt11:[],
    CTHfacultyAt12:[],
    CTHfacultyAt03:[],
    CTHfacultyAt04:[],

    CFfacultyAt9:[],
    CFfacultyAt10:[],
    CFfacultyAt11:[],
    CFfacultyAt12:[],
    CFfacultyAt03:[],
    CFfacultyAt04:[],

    PMfacultyAt9:[],
    PMfacultyAt10:[],
    PMfacultyAt11:[],
    PMfacultyAt12:[],
    PMfacultyAt03:[],
    PMfacultyAt04:[],

    PTfacultyAt9:[],
    PTfacultyAt10:[],
    PTfacultyAt11:[],
    PTfacultyAt12:[],
    PTfacultyAt03:[],
    PTfacultyAt04:[],

    PWfacultyAt9:[],
    PWfacultyAt10:[],
    PWfacultyAt11:[],
    PWfacultyAt12:[],
    PWfacultyAt03:[],
    PWfacultyAt04:[],

    PTHfacultyAt9:[],
    PTHfacultyAt10:[],
    PTHfacultyAt11:[],
    PTHfacultyAt12:[],
    PTHfacultyAt03:[],
    PTHfacultyAt04:[],

    PFfacultyAt9:[],
    PFfacultyAt10:[],
    PFfacultyAt11:[],
    PFfacultyAt12:[],
    PFfacultyAt03:[],
    PFfacultyAt04:[],

}

const reducer=(state,action)=>{

    switch(action.type){
        case'MADD_TO_9':
        return{
            ...state,
            MfacultyAt9:[...state.MfacultyAt9,action.item]
        }
        case'MADD_TO_10':
        return{
            ...state,
            MfacultyAt10:[...state.MfacultyAt10,action.item]
        }
        case'MADD_TO_11':
        return{
            ...state,
            MfacultyAt11:[...state.MfacultyAt11,action.item]
        }
        case'MADD_TO_12':
        return{
            ...state,
            MfacultyAt12:[...state.MfacultyAt12,action.item]
        }
        case'MADD_TO_03':
        return{
            ...state,
            MfacultyAt03:[...state.MfacultyAt03,action.item]
        }
        case'MADD_TO_04':
        return{
            ...state,
            MfacultyAt04:[...state.MfacultyAt04,action.item]
        }

        case'TADD_TO_9':
        return{
            ...state,
            TfacultyAt9:[...state.TfacultyAt9,action.item]
        }
        case'TADD_TO_10':
        return{
            ...state,
            TfacultyAt10:[...state.TfacultyAt10,action.item]
        }
        case'TADD_TO_11':
        return{
            ...state,
            TfacultyAt11:[...state.TfacultyAt11,action.item]
        }
        case'TADD_TO_12':
        return{
            ...state,
            TfacultyAt12:[...state.TfacultyAt12,action.item]
        }
        case'TADD_TO_03':
        return{
            ...state,
            TfacultyAt03:[...state.TfacultyAt03,action.item]
        }
        case'TADD_TO_04':
        return{
            ...state,
            TfacultyAt04:[...state.TfacultyAt04,action.item]
        }

        case'WADD_TO_9':
        return{
            ...state,
            WfacultyAt9:[...state.WfacultyAt9,action.item]
        }
        case'WADD_TO_10':
        return{
            ...state,
            WfacultyAt10:[...state.WfacultyAt10,action.item]
        }
        case'WADD_TO_11':
        return{
            ...state,
            WfacultyAt11:[...state.WfacultyAt11,action.item]
        }
        case'WADD_TO_12':
        return{
            ...state,
            WfacultyAt12:[...state.WfacultyAt12,action.item]
        }
        case'WADD_TO_03':
        return{
            ...state,
            WfacultyAt03:[...state.WfacultyAt03,action.item]
        }
        case'WADD_TO_04':
        return{
            ...state,
            WfacultyAt04:[...state.WfacultyAt04,action.item]
        }

        case'THADD_TO_9':
        return{
            ...state,
            THfacultyAt9:[...state.THfacultyAt9,action.item]
        }
        case'THADD_TO_10':
        return{
            ...state,
            THfacultyAt10:[...state.THfacultyAt10,action.item]
        }
        case'THADD_TO_11':
        return{
            ...state,
            THfacultyAt11:[...state.THfacultyAt11,action.item]
        }
        case'THADD_TO_12':
        return{
            ...state,
            THfacultyAt12:[...state.THfacultyAt12,action.item]
        }
        case'THADD_TO_03':
        return{
            ...state,
            THfacultyAt03:[...state.THfacultyAt03,action.item]
        }
        case'THADD_TO_04':
        return{
            ...state,
            THfacultyAt04:[...state.THfacultyAt04,action.item]
        }

        case'FADD_TO_9':
        return{
            ...state,
            FfacultyAt9:[...state.FfacultyAt9,action.item]
        }
        case'FADD_TO_10':
        return{
            ...state,
            FfacultyAt10:[...state.FfacultyAt10,action.item]
        }
        case'FADD_TO_11':
        return{
            ...state,
            FfacultyAt11:[...state.FfacultyAt11,action.item]
        }
        case'FADD_TO_12':
        return{
            ...state,
            FfacultyAt12:[...state.FfacultyAt12,action.item]
        }
        case'FADD_TO_03':
        return{
            ...state,
            FfacultyAt03:[...state.FfacultyAt03,action.item]
        }
        case'FADD_TO_04':
        return{
            ...state,
            FfacultyAt04:[...state.FfacultyAt04,action.item]
        }




        case'PMADD_TO_9':
        return{
            ...state,
            PMfacultyAt9:[...state.PMfacultyAt9,action.item]
        }
        case'PMADD_TO_10':
        return{
            ...state,
            PMfacultyAt10:[...state.PMfacultyAt10,action.item]
        }
        case'PMADD_TO_11':
        return{
            ...state,
            PMfacultyAt11:[...state.PMfacultyAt11,action.item]
        }
        case'PMADD_TO_12':
        return{
            ...state,
            PMfacultyAt12:[...state.PMfacultyAt12,action.item]
        }
        case'PMADD_TO_03':
        return{
            ...state,
            PMfacultyAt03:[...state.PMfacultyAt03,action.item]
        }
        case'PMADD_TO_04':
        return{
            ...state,
            PMfacultyAt04:[...state.PMfacultyAt04,action.item]
        }

        case'PTADD_TO_9':
        return{
            ...state,
            PTfacultyAt9:[...state.PTfacultyAt9,action.item]
        }
        case'PTADD_TO_10':
        return{
            ...state,
            PTfacultyAt10:[...state.PTfacultyAt10,action.item]
        }
        case'PTADD_TO_11':
        return{
            ...state,
            PTfacultyAt11:[...state.PTfacultyAt11,action.item]
        }
        case'PTADD_TO_12':
        return{
            ...state,
            PTfacultyAt12:[...state.PTfacultyAt12,action.item]
        }
        case'PTADD_TO_03':
        return{
            ...state,
            PTfacultyAt03:[...state.PTfacultyAt03,action.item]
        }
        case'PTADD_TO_04':
        return{
            ...state,
            PTfacultyAt04:[...state.PTfacultyAt04,action.item]
        }

        case'PWADD_TO_9':
        return{
            ...state,
            PWfacultyAt9:[...state.PWfacultyAt9,action.item]
        }
        case'PWADD_TO_10':
        return{
            ...state,
            PWfacultyAt10:[...state.PWfacultyAt10,action.item]
        }
        case'PWADD_TO_11':
        return{
            ...state,
            PWfacultyAt11:[...state.PWfacultyAt11,action.item]
        }
        case'PWADD_TO_12':
        return{
            ...state,
            PWfacultyAt12:[...state.PWfacultyAt12,action.item]
        }
        case'PWADD_TO_03':
        return{
            ...state,
            PWfacultyAt03:[...state.PWfacultyAt03,action.item]
        }
        case'PWADD_TO_04':
        return{
            ...state,
            PWfacultyAt04:[...state.PWfacultyAt04,action.item]
        }

        case'PTHADD_TO_9':
        return{
            ...state,
            PTHfacultyAt9:[...state.PTHfacultyAt9,action.item]
        }
        case'PTHADD_TO_10':
        return{
            ...state,
            PTHfacultyAt10:[...state.PTHfacultyAt10,action.item]
        }
        case'PTHADD_TO_11':
        return{
            ...state,
            PTHfacultyAt11:[...state.PTHfacultyAt11,action.item]
        }
        case'PTHADD_TO_12':
        return{
            ...state,
            PTHfacultyAt12:[...state.PTHfacultyAt12,action.item]
        }
        case'PTHADD_TO_03':
        return{
            ...state,
            PTHfacultyAt03:[...state.PTHfacultyAt03,action.item]
        }
        case'PTHADD_TO_04':
        return{
            ...state,
            PTHfacultyAt04:[...state.PTHfacultyAt04,action.item]
        }

        case'PFADD_TO_9':
        return{
            ...state,
            PFfacultyAt9:[...state.PFfacultyAt9,action.item]
        }
        case'PFADD_TO_10':
        return{
            ...state,
            PFfacultyAt10:[...state.PFfacultyAt10,action.item]
        }
        case'PFADD_TO_11':
        return{
            ...state,
            PFfacultyAt11:[...state.PFfacultyAt11,action.item]
        }
        case'PFADD_TO_12':
        return{
            ...state,
            PFfacultyAt12:[...state.PFfacultyAt12,action.item]
        }
        case'PFADD_TO_03':
        return{
            ...state,
            PFfacultyAt03:[...state.PFfacultyAt03,action.item]
        }
        case'PFADD_TO_04':
        return{
            ...state,
            PFfacultyAt04:[...state.PFfacultyAt04,action.item]
        }



        case'CMADD_TO_9':
        return{
            ...state,
            CMfacultyAt9:[...state.CMfacultyAt9,action.item]
        }
        case'CMADD_TO_10':
        return{
            ...state,
            CMfacultyAt10:[...state.CMfacultyAt10,action.item]
        }
        case'CMADD_TO_11':
        return{
            ...state,
            CMfacultyAt11:[...state.CMfacultyAt11,action.item]
        }
        case'CMADD_TO_12':
        return{
            ...state,
            CMfacultyAt12:[...state.CMfacultyAt12,action.item]
        }
        case'CMADD_TO_03':
        return{
            ...state,
            CMfacultyAt03:[...state.CMfacultyAt03,action.item]
        }
        case'CMADD_TO_04':
        return{
            ...state,
            CMfacultyAt04:[...state.CMfacultyAt04,action.item]
        }

        case'CTADD_TO_9':
        return{
            ...state,
            CTfacultyAt9:[...state.CTfacultyAt9,action.item]
        }
        case'CTADD_TO_10':
        return{
            ...state,
            CTfacultyAt10:[...state.CTfacultyAt10,action.item]
        }
        case'CTADD_TO_11':
        return{
            ...state,
            CTfacultyAt11:[...state.CTfacultyAt11,action.item]
        }
        case'CTADD_TO_12':
        return{
            ...state,
            CTfacultyAt12:[...state.CTfacultyAt12,action.item]
        }
        case'CTADD_TO_03':
        return{
            ...state,
            CTfacultyAt03:[...state.CTfacultyAt03,action.item]
        }
        case'CTADD_TO_04':
        return{
            ...state,
            CTfacultyAt04:[...state.CTfacultyAt04,action.item]
        }

        case'CWADD_TO_9':
        return{
            ...state,
            CWfacultyAt9:[...state.CWfacultyAt9,action.item]
        }
        case'CWADD_TO_10':
        return{
            ...state,
            CWfacultyAt10:[...state.CWfacultyAt10,action.item]
        }
        case'CWADD_TO_11':
        return{
            ...state,
            CWfacultyAt11:[...state.CWfacultyAt11,action.item]
        }
        case'CWADD_TO_12':
        return{
            ...state,
            CWfacultyAt12:[...state.CWfacultyAt12,action.item]
        }
        case'CWADD_TO_03':
        return{
            ...state,
            CWfacultyAt03:[...state.CWfacultyAt03,action.item]
        }
        case'CWADD_TO_04':
        return{
            ...state,
            CWfacultyAt04:[...state.CWfacultyAt04,action.item]
        }

        case'CTHADD_TO_9':
        return{
            ...state,
            CTHfacultyAt9:[...state.CTHfacultyAt9,action.item]
        }
        case'CTHADD_TO_10':
        return{
            ...state,
            CTHfacultyAt10:[...state.CTHfacultyAt10,action.item]
        }
        case'CTHADD_TO_11':
        return{
            ...state,
            CTHfacultyAt11:[...state.CTHfacultyAt11,action.item]
        }
        case'CTHADD_TO_12':
        return{
            ...state,
            CTHfacultyAt12:[...state.CTHfacultyAt12,action.item]
        }
        case'CTHADD_TO_03':
        return{
            ...state,
            CTHfacultyAt03:[...state.CTHfacultyAt03,action.item]
        }
        case'CTHADD_TO_04':
        return{
            ...state,
            CTHfacultyAt04:[...state.CTHfacultyAt04,action.item]
        }

        case'CFADD_TO_9':
        return{
            ...state,
            CFfacultyAt9:[...state.CFfacultyAt9,action.item]
        }
        case'CFADD_TO_10':
        return{
            ...state,
            CFfacultyAt10:[...state.CFfacultyAt10,action.item]
        }
        case'CFADD_TO_11':
        return{
            ...state,
            CFfacultyAt11:[...state.CFfacultyAt11,action.item]
        }
        case'CFADD_TO_12':
        return{
            ...state,
            CFfacultyAt12:[...state.CFfacultyAt12,action.item]
        }
        case'CFADD_TO_03':
        return{
            ...state,
            CFfacultyAt03:[...state.CFfacultyAt03,action.item]
        }
        case'CFADD_TO_04':
        return{
            ...state,
            CFfacultyAt04:[...state.CFfacultyAt04,action.item]
        }
    }
    
}
export default reducer