export const initialState={
    MfacultyAt9:[],
    MfacultyAt10:[],
    MfacultyAt11:[],
    MfacultyAt12:[],
    MfacultyAt03:[],
    MfacultyAt04:[],

    TfacultyAt9:[],
    TfacultyAt10:[],
    TfacultyAt11:[],
    TfacultyAt12:[],
    TfacultyAt03:[],
    TfacultyAt04:[],

    WfacultyAt9:[],
    WfacultyAt10:[],
    WfacultyAt11:[],
    WfacultyAt12:[],
    WfacultyAt03:[],
    WfacultyAt04:[],

    THfacultyAt9:[],
    THfacultyAt10:[],
    THfacultyAt11:[],
    THfacultyAt12:[],
    THfacultyAt03:[],
    THfacultyAt04:[],

    FfacultyAt9:[],
    FfacultyAt10:[],
    FfacultyAt11:[],
    FfacultyAt12:[],
    FfacultyAt03:[],
    FfacultyAt04:[],
}

const reducer=(state,action)=>{

    switch(action.type){
        case'MADD_TO_9':
        return{
            ...state,
            MfacultyAt9:[...state.MfacultyAt9,action.item]
        }
        case'MADD_TO_10':
        return{
            ...state,
            MfacultyAt10:[...state.MfacultyAt10,action.item]
        }
        case'MADD_TO_11':
        return{
            ...state,
            MfacultyAt11:[...state.MfacultyAt11,action.item]
        }
        case'MADD_TO_12':
        return{
            ...state,
            MfacultyAt12:[...state.MfacultyAt12,action.item]
        }
        case'MADD_TO_03':
        return{
            ...state,
            MfacultyAt03:[...state.MfacultyAt03,action.item]
        }
        case'MADD_TO_04':
        return{
            ...state,
            MfacultyAt04:[...state.MfacultyAt04,action.item]
        }

        case'TADD_TO_9':
        return{
            ...state,
            TfacultyAt9:[...state.TfacultyAt9,action.item]
        }
        case'TADD_TO_10':
        return{
            ...state,
            TfacultyAt10:[...state.TfacultyAt10,action.item]
        }
        case'TADD_TO_11':
        return{
            ...state,
            TfacultyAt11:[...state.TfacultyAt11,action.item]
        }
        case'TADD_TO_12':
        return{
            ...state,
            TfacultyAt12:[...state.TfacultyAt12,action.item]
        }
        case'TADD_TO_03':
        return{
            ...state,
            TfacultyAt03:[...state.TfacultyAt03,action.item]
        }
        case'TADD_TO_04':
        return{
            ...state,
            TfacultyAt04:[...state.TfacultyAt04,action.item]
        }

        case'WADD_TO_9':
        return{
            ...state,
            WfacultyAt9:[...state.WfacultyAt9,action.item]
        }
        case'WADD_TO_10':
        return{
            ...state,
            WfacultyAt10:[...state.WfacultyAt10,action.item]
        }
        case'WADD_TO_11':
        return{
            ...state,
            WfacultyAt11:[...state.WfacultyAt11,action.item]
        }
        case'WADD_TO_12':
        return{
            ...state,
            WfacultyAt12:[...state.WfacultyAt12,action.item]
        }
        case'WADD_TO_03':
        return{
            ...state,
            WfacultyAt03:[...state.WfacultyAt03,action.item]
        }
        case'WADD_TO_04':
        return{
            ...state,
            WfacultyAt04:[...state.WfacultyAt04,action.item]
        }

        case'THADD_TO_9':
        return{
            ...state,
            THfacultyAt9:[...state.THfacultyAt9,action.item]
        }
        case'THADD_TO_10':
        return{
            ...state,
            THfacultyAt10:[...state.THfacultyAt10,action.item]
        }
        case'THADD_TO_11':
        return{
            ...state,
            THfacultyAt11:[...state.THfacultyAt11,action.item]
        }
        case'THADD_TO_12':
        return{
            ...state,
            THfacultyAt12:[...state.THfacultyAt12,action.item]
        }
        case'THADD_TO_03':
        return{
            ...state,
            THfacultyAt03:[...state.THfacultyAt03,action.item]
        }
        case'THADD_TO_04':
        return{
            ...state,
            THfacultyAt04:[...state.THfacultyAt04,action.item]
        }

        case'FADD_TO_9':
        return{
            ...state,
            FfacultyAt9:[...state.FfacultyAt9,action.item]
        }
        case'FADD_TO_10':
        return{
            ...state,
            FfacultyAt10:[...state.FfacultyAt10,action.item]
        }
        case'FADD_TO_11':
        return{
            ...state,
            FfacultyAt11:[...state.FfacultyAt11,action.item]
        }
        case'FADD_TO_12':
        return{
            ...state,
            FfacultyAt12:[...state.FfacultyAt12,action.item]
        }
        case'FADD_TO_03':
        return{
            ...state,
            FfacultyAt03:[...state.FfacultyAt03,action.item]
        }
        case'FADD_TO_04':
        return{
            ...state,
            FfacultyAt04:[...state.FfacultyAt04,action.item]
        }
    }
    
}
export default reducer